spring.application.name=guider
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Guide2030
spring.datasource.username=postgres
spring.datasource.password=Support@2525

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=guide2030SecretKey
jwt.expiration=86400000
